### ISSUE TITLE
The menu item is not responding

### ISSUE THREAD

**Issue by berlintapondjou** [berlintapondjou/devops#1]
The menu item is not responding, please correct it.

**Comment by bipeensinha** [comment]
Hey Berline , I am working on it , will update in a day
![Uploading powersheel4JPG.JPG…]()

**Comment by berlintapondjou** [comment]
Please, keep me updated.

**Comment by bipeensinha** [comment]
Hey Berline i have updated the new code . Please close this issues now

**Comment by berlintapondjou** [comment]
Let me close this issue.
